## Data Analysis With Numpy
### (Numerical Python)

In [1]:
arr = [1, 2, 3]
print(arr)

[1, 2, 3]


In [2]:
print(arr*5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [3]:
# ndarray - main object of numpy
# all element has same data type inside ndarray
# faster mathematical operations

In [4]:
import numpy as np
arr1 = np.array(arr)
print(arr1)
arr1 = arr1*5
print(arr1)

[1 2 3]
[ 5 10 15]


In [5]:
arr2 = np.array([1, 1.9, 'gdgk',])
arr2

array(['1', '1.9', 'gdgk'], dtype='<U32')

## Ndarray

In [6]:
# 1D array
arr1 = np.array([2, 6, 7])
print(arr1)

# 2D array
arr2 = np.array([
    [1, 2, 3],  # row1
    [4, 5, 6]   # row2
])
print(arr2)

# 3D array
arr3 = np.array([
    [[1, 2, 3], [4, 5, 6]],  # first floor
    [[1, 2, 3], [4, 5, 6]],  # 2nd floor
    [[1, 2, 3], [4, 5, 6]],  # 3rd floor
])
print(arr3)


[2 6 7]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### Array Attribute

In [7]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

# data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(3,)
(2, 3)
(3, 2, 3)
int64
int64
int64
3
6
18


#### Data type

In [8]:
arr = np.array([1,2,3.2])
# upcasted to floatData
print(arr.dtype)

arr = np.array([1,1.3,'hello'])
# upcasted to string
print(arr.dtype)

arr = np.array([1,1.3,'hello',True])
print(arr.dtype)

float64
<U32
<U32


### Selecting a data type for an array

In [9]:
arr = np.array([1,2,300], dtype = np.int16)
print(arr.dtype)
print(arr)

# alternative way
arr = arr.astype(np.int32)
print(arr.dtype)

# error
arr = np.array([1,1.2,'hello',True], dtype = np.float64)
print(arr.dtype)

int16
[  1   2 300]
int32


ValueError: could not convert string to float: 'hello'

## Ndarray creation from existing data

In [ ]:
# list

lst = [10, 20, 30, 40, 40.5]
arr = np.array(lst, dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)

mixed_lst = [10, True, 'Hello']
arr = np.array(mixed_lst)
print(arr)
print(type(arr))
print(arr.dtype)

matrix = [
    [1, 2, 3],
    [4, 5, 6]
]
arr = np.array(matrix)
print(arr)
print(type(arr))
print(arr.dtype)

In [ ]:
# tuple

tpl = (10, 20, 30)
arr = np.array(tpl, dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)

arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)

print(arr.shape)
print(arr.ndim)

In [ ]:
# set -> directly pass make as a object

st = {1, 2, 3}
arr = np.array(st)
print(arr)
print(type(arr))
print(arr.dtype)

In [ ]:
arr = np.array(list(st))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)

In [ ]:
# dictionary

dc = {'a': 10, 'b': 20, 'c': 30}

keys = dc.keys()
values = dc.values()
items = dc.items()

print(keys)
print(type(keys))

print(values)
print(type(values))

print(items)
print(type(items))

In [ ]:
# keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
# values to ndarray
arr = np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
# items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

## Creating ndarray from scratch

In [ ]:
# np.zeros

arr = np.zeros(3)
print(arr)

arr = np.zeros(3, dtype=np.int16)
print(arr)

arr = np.zeros((2, 3), dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.zeros_like(arr3)
print(arr)
print(arr.shape)

In [ ]:
# np.ones

arr = np.ones((2, 3), dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.ones_like(arr3)
print(arr)
print(arr.shape)

In [ ]:
# np.empty -> random value

arr = np.empty((2, 3), dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.empty_like(arr3)
print(arr)
print(arr.shape)

In [ ]:
# np.full

arr = np.full((2, 3), np.inf)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.full_like(arr3, 20, dtype=np.float32)
print(arr)
print(arr.shape)

## Array creation with random values

In [ ]:
# np.random.rand(shape) : 0->1

arr = np.random.rand(2, 3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
# np.random.randint(start, end, shape)

arr = np.random.randint(1, 10, (2, 3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
# np.random.uniform(start, end, shape)

arr = np.random.uniform(1, 10, (2, 3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

### Array creation with range functions

In [ ]:
# np.arange(first, end, step) -> similar to range function

arr = np.arange(1, 10, 1)
print(arr)

mat = arr.reshape(3, 2)
print(mat)
print(type(mat))
print(mat.dtype)
print(mat.shape)
print(mat.ndim)
print(mat.size)

In [ ]:
mat = arr.reshape(3, 3)
print(mat)
print(type(mat))
print(mat.dtype)
print(mat.shape)
print(mat.ndim)
print(mat.size)

In [ ]:
# np.linspace(start, end(included), how much)

arr = np.linspace(0, 4, 6)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
# np.logspace(start, end(included), how much)

arr = np.logspace(0, 4, 6)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
arr = np.logspace(0, 4, 6, base=2)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

## Creating matrix for linear algebra

In [ ]:
# diagonal matrix

diagonal_matrix = np.diag([1, 2, 3, 4])
print(diagonal_matrix)
print(diagonal_matrix.shape)

diagonal_matrix = np.diag([1, 2, 3, 4], 1)
print(diagonal_matrix)
print(diagonal_matrix.shape)

In [ ]:
# Identity matrix

identity_mat = np.eye(4)
print(identity_mat)
print(identity_mat.shape)

identity_mat = np.eye(4, 5)  # row, col
print(identity_mat)
print(identity_mat.shape)

identity_mat = np.eye(4, 5, -1)  # row, col, k
print(identity_mat)
print(identity_mat.shape)

## Indexing & Slicing

In [ ]:
# indexing

print(arr1)
print(arr2)

arr1[2] = 100
print(arr1)

arr2[0, 1] = 200
print(arr2)

In [ ]:
# slicing

arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr1)

mod_arr1 = arr1[0: 7: 2]  # start: end: step
print(arr1)
print(mod_arr1)

arr1[2] = 100
print(arr1)
print(mod_arr1)  # automaticly change 

arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
mod_arr1 = arr1[0: 7: 2].copy()  # start: end: step
print(arr1)
print(mod_arr1)
arr1[2] = 100
print(mod_arr1)

In [ ]:
# 2D slicing
# arr[row_start: row_end: step, col_start: col_end: step]  -> end(excluded)

print(arr2)

# getting a row
row_0 = arr2[0:1,]
print(row_0)

row_0 = arr2[:1,]
print(row_0)

arr2[0][1] = 2
print(row_0)

print(arr2)

# getting a column
col_0 = arr2[:, :1]
print(col_0)
col_1 = arr2[::, 1:2]
print(col_1)
col_1 = arr2[::, 1:]
print(col_1)

In [ ]:
# getting a portion

print(arr2)

portion = arr2[::, 0:2]
print(portion)

## Advanced Indexing

In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr)

values = arr[[0, 3, 1]]
print(values)

In [ ]:
print(arr2)

print(arr2[[0, 1], [1, 2]])

# using something boolean
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1)
print(arr1 > 1)
print(arr2)
print(arr2[arr1 > 1])

In [ ]:
# using something boolean
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
print(arr1 > 1)
print(arr2)
print(arr2[arr1 > 1])

In [ ]:
print(arr2)

arr2[arr2 > 2] = 0
print(arr2)

### Iterating over arrays

In [ ]:
arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(arr3)

In [ ]:
# For a 3D array
for matrix in arr3:
    for row in matrix:
        for element in row:
            print(element)

In [ ]:
for i in np.nditer(arr3):
    print(i)

### Practice Problems

1: You have a list of temperatures recorded in Celsius.
   
Your task is to:\
Create a NumPy array from the given list.\
Convert all temperatures from Celsius to Fahrenheit. The formula is F = C* 1.8 + 32.\
Print the new Fahrenheit array.


In [10]:
given_temp = [20, 21, 23, 15, 10, 35, 40, 52, 28, 19]
temp = np.array(given_temp)
print(temp)

temp = temp*1.8+32
print(temp)

[20 21 23 15 10 35 40 52 28 19]
[ 68.   69.8  73.4  59.   50.   95.  104.  125.6  82.4  66.2]


2.  You have a Python list containing the lap times (in seconds) for an athlete.\
Task:

Convert the list into a NumPy array.\
Print the array's shape, size, and data type.\
The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.\
Print the new array of lap times in minutes.

In [11]:
lst = [10, 20, 30, 40, 50]
arr = np.array(lst)
print(arr.shape)
print(arr.size)
print(arr.dtype)

(5,)
5
int64


In [13]:
lap_time = np.array([2000, 78899, 88999, 4444, 443323, 23444])  # given in seconds
lap_time = lap_time//60  # convert to minutes
print(lap_time)

[  33 1314 1483   74 7388  390]
